-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.128.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 3/10/2018 8:24:09 AM
-- Server version: 5.1.41
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE llcdh;

--
-- Definition for table admin
--
DROP TABLE IF EXISTS admin;
CREATE TABLE admin (
  admin_id INT(11) NOT NULL,
  firstname VARCHAR(100) NOT NULL,
  middlename VARCHAR(100) NOT NULL,
  lastname VARCHAR(100) NOT NULL,
  username VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  confirm_password VARCHAR(100) NOT NULL,
  admin_image VARCHAR(100) NOT NULL,
  admin_type VARCHAR(100) NOT NULL,
  admin_rol INT(11) DEFAULT NULL,
  admin_status INT(11) NOT NULL,
  admin_added DATETIME NOT NULL,
  PRIMARY KEY (admin_id),
  UNIQUE INDEX admin_id (admin_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 2730
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table billings
--
DROP TABLE IF EXISTS billings;
CREATE TABLE billings (
  bill_id INT(11) NOT NULL AUTO_INCREMENT,
  bill_name VARCHAR(255) DEFAULT NULL,
  bill_price DECIMAL(10, 0) DEFAULT NULL,
  bill_ptrans_id VARCHAR(255) DEFAULT NULL,
  bill_patient_id VARCHAR(255) DEFAULT NULL,
  bill_date DATETIME DEFAULT NULL,
  PRIMARY KEY (bill_id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 69
AVG_ROW_LENGTH = 60
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table laboratory
--
DROP TABLE IF EXISTS laboratory;
CREATE TABLE laboratory (
  lab_id INT(11) NOT NULL AUTO_INCREMENT,
  lab_name VARCHAR(50) DEFAULT NULL,
  lab_price DECIMAL(19, 2) DEFAULT NULL,
  lab_date_added DATETIME DEFAULT NULL,
  PRIMARY KEY (lab_id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 14
AVG_ROW_LENGTH = 42
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table med_billings
--
DROP TABLE IF EXISTS med_billings;
CREATE TABLE med_billings (
  mb_id INT(11) NOT NULL AUTO_INCREMENT,
  mb_desc VARCHAR(255) DEFAULT NULL,
  mb_qty SMALLINT(6) DEFAULT NULL,
  mb_price DECIMAL(19, 2) DEFAULT NULL,
  mb_total DECIMAL(10, 0) DEFAULT NULL,
  patient_trans_id VARCHAR(255) DEFAULT NULL,
  mb_date DATE DEFAULT NULL,
  PRIMARY KEY (mb_id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 18
AVG_ROW_LENGTH = 69
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table medicine
--
DROP TABLE IF EXISTS medicine;
CREATE TABLE medicine (
  med_id INT(11) NOT NULL AUTO_INCREMENT,
  med_name VARCHAR(50) DEFAULT NULL,
  med_qty SMALLINT(6) DEFAULT NULL,
  med_in SMALLINT(6) DEFAULT NULL,
  med_out SMALLINT(6) DEFAULT NULL,
  med_price DECIMAL(10, 0) DEFAULT NULL,
  med_date_added DATETIME DEFAULT NULL,
  med_status VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (med_id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 12
AVG_ROW_LENGTH = 55
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table patient_transaction
--
DROP TABLE IF EXISTS patient_transaction;
CREATE TABLE patient_transaction (
  id INT(11) NOT NULL AUTO_INCREMENT,
  patient_trans_id VARCHAR(255) DEFAULT NULL,
  patient_id VARCHAR(255) DEFAULT NULL,
  incharge_doc VARCHAR(255) DEFAULT NULL,
  patient_ward_no VARCHAR(255) DEFAULT NULL,
  patient_bed_no INT(11) DEFAULT NULL,
  patient_date_discharge DATETIME DEFAULT NULL,
  patient_findings VARCHAR(255) DEFAULT NULL,
  patient_doc_prescription VARCHAR(255) DEFAULT NULL,
  patient_soa VARCHAR(255) DEFAULT NULL,
  patient_date_incharge DATE DEFAULT NULL,
  patient_total_bills VARCHAR(255) DEFAULT NULL,
  patient_status VARCHAR(255) DEFAULT NULL,
  patient_tender_amount VARCHAR(255) DEFAULT NULL,
  patient_change VARCHAR(255) DEFAULT NULL,
  patient_remarks VARCHAR(255) DEFAULT NULL,
  patient_amount_disc DECIMAL(8, 2) DEFAULT NULL,
  patient_total_discounted DECIMAL(10, 0) DEFAULT NULL,
  patient_type_disc VARCHAR(255) DEFAULT NULL,
  patient_discountId VARCHAR(255) DEFAULT NULL,
  patient_discSponsor VARCHAR(255) DEFAULT NULL,
  patient_detDiscount VARCHAR(255) DEFAULT NULL,
  patient_admit_diagnos VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 84
AVG_ROW_LENGTH = 100
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table patient_vsr
--
DROP TABLE IF EXISTS patient_vsr;
CREATE TABLE patient_vsr (
  vsr_id INT(11) NOT NULL AUTO_INCREMENT,
  patient_trans_id VARCHAR(255) DEFAULT NULL,
  vsr_temp VARCHAR(255) DEFAULT NULL,
  vsr_bp VARCHAR(255) DEFAULT NULL,
  vsr_pr VARCHAR(255) DEFAULT NULL,
  vsr_rr VARCHAR(255) DEFAULT NULL,
  vsr_date DATETIME DEFAULT NULL,
  PRIMARY KEY (vsr_id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 60
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table user
--
DROP TABLE IF EXISTS user;
CREATE TABLE user (
  user_id INT(11) NOT NULL AUTO_INCREMENT,
  patient_id VARCHAR(100) NOT NULL,
  firstname VARCHAR(100) NOT NULL,
  middlename VARCHAR(100) NOT NULL,
  lastname VARCHAR(100) NOT NULL,
  contact VARCHAR(100) NOT NULL,
  gender VARCHAR(100) NOT NULL,
  guardian VARCHAR(100) DEFAULT NULL,
  address VARCHAR(100) NOT NULL,
  status VARCHAR(100) NOT NULL,
  religion VARCHAR(255) DEFAULT NULL,
  age VARCHAR(255) DEFAULT NULL,
  birthdate DATE DEFAULT NULL,
  remarks VARCHAR(255) DEFAULT NULL,
  date_added DATETIME NOT NULL,
  PRIMARY KEY (user_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 56
AVG_ROW_LENGTH = 1489
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table admin
--
INSERT INTO admin VALUES
(20181901, 'Jendy', 'Villamor', 'Manatad', 'admin', 'admin', 'admin', '13-1.jpg', 'Administrator', 1, 1, '2018-03-08 00:00:00'),
(20181902, 'Hyacinth Mae', 'G', 'Cipres', 'nurse', 'nurse', 'nurse', 'piZap_1394237757548.jpg', 'Nurse', 2, 1, '2018-03-08 05:03:28'),
(20181903, 'Gene Rose', 'G', 'Obregon', 'doctor', 'doctor', 'doctor', '2016-12-02-02-25-03--1149275481.jpeg', 'Doctor', 2, 0, '2018-03-08 05:16:36'),
(20181904, 'Pedra', 'C', 'Cruz', 'cashier', 'cashier', 'cashier', '1.jpg', 'Cashier', 2, 1, '0000-00-00 00:00:00'),
(20181905, 'Jenny', 'V', 'Manatad', 'pharmacist', 'pharmacist', 'pharmacist', '7.jpg', 'Pharmacist', 2, 1, '0000-00-00 00:00:00'),
(20181906, 'Jury', 'V', 'Manatad', 'clerk', 'clerk', 'clerk', 'Alessandro_Volta.jpeg', 'Clerk', 2, 1, '0000-00-00 00:00:00'),
(20181907, 'Jeffrey', 'V', 'Manatad', 'billings', 'billings', 'billings', '20140914_151037-1.jpg', 'Billings', 2, 1, '0000-00-00 00:00:00'),
(20181908, 'Michael', 'V', 'Manatad', 'laboratory', 'laboratory', 'laboratory', '20151202_153742~2~2.jpg', 'Laboratory', 2, 1, '0000-00-00 00:00:00'),
(20181909, 'Michael', 'V', 'Manatad', 'michael', '123456', '123456', '20160328_172143.jpg', 'Doctor', 2, 1, '0000-00-00 00:00:00'),
(201819010, 'Dominga', 'V. ', 'Manatad', 'dominga', '123456', '123456', '20160403_204911.jpg', 'Doctor', 2, 1, '0000-00-00 00:00:00');

-- 
-- Dumping data for table billings
--
INSERT INTO billings VALUES
(67, 'Urinalysis', 40, '000003005', '000003', '2018-03-09 19:10:40'),
(46, 'Blood Typing', 100, '000001004', '000001', '2018-03-08 18:25:07'),
(47, 'NS1 dengue test', 1100, '000002003', '000002', '2018-03-08 19:13:22'),
(48, 'Select Laboratory', 0, '000001004', '000001', '2018-03-08 21:33:09'),
(49, 'Select Laboratory', 0, '000001004', '000001', '2018-03-08 21:33:09'),
(68, 'Blood Uric Acid', 100, '000003005', '000003', '2018-03-09 19:11:58'),
(54, 'Blood Typing', 100, '000006009', '000006', '2018-03-09 07:39:40'),
(55, 'Blood Typing', 100, '000006009', '000006', '2018-03-09 07:39:40'),
(56, 'PSA', 950, '000006009', '000006', '2018-03-09 07:39:50'),
(57, 'PSA', 950, '000006009', '000006', '2018-03-09 07:39:50'),
(58, 'Blood Typing', 100, '000006009', '000006', '2018-03-09 07:40:07'),
(59, 'Blood Typing', 100, '000006009', '000006', '2018-03-09 07:40:07'),
(60, 'CBC', 100, '000006009', '000006', '2018-03-09 07:40:52'),
(61, 'CBC', 100, '000006009', '000006', '2018-03-09 07:40:52'),
(62, 'CBC', 100, '000006009', '000006', '2018-03-09 07:42:27'),
(63, 'Stool Routine Exam', 40, '000006009', '000006', '2018-03-09 07:42:39'),
(64, 'NS1 dengue test', 1100, '000001007', '000001', '2018-03-09 09:17:01'),
(65, 'PSA', 950, '000004008', '000004', '2018-03-09 17:08:53'),
(66, 'HBsAg', 150, '000004008', '000004', '2018-03-09 17:10:01');

-- 
-- Dumping data for table laboratory
--
INSERT INTO laboratory VALUES
(1, 'CBC', 100.00, '2018-03-07 23:42:05'),
(2, 'PSA', 950.00, '2018-03-07 23:42:09'),
(3, 'Blood Typing', 100.00, '2018-03-09 00:06:29'),
(4, 'NS1 dengue test', 1100.00, '2018-03-09 00:04:50'),
(5, 'HBsAg', 150.00, '2018-03-09 00:07:59'),
(6, 'Pregnancy Test', 120.00, '2018-03-09 00:08:24'),
(7, 'Urinalysis', 40.00, '2018-03-09 00:08:42'),
(8, 'Stool Routine Exam', 40.00, '2018-03-09 00:09:04'),
(9, 'Albumine', 100.00, '2018-03-09 00:09:21'),
(10, 'Blood Urea Nitrogen', 85.00, '2018-03-09 00:09:47'),
(11, 'Blood Uric Acid', 100.00, '2018-03-09 00:10:42'),
(12, 'Creatinine', 85.00, '2018-03-09 00:11:00'),
(13, 'FBS', 85.00, '2018-03-09 00:12:17');

-- 
-- Dumping data for table med_billings
--
INSERT INTO med_billings VALUES
(11, 'Kispirin 10mg', 2, 500.00, 1000, '000004008', '2018-03-09'),
(12, 'Nifedipine 10mg', 5, 10.00, 50, '000004008', '2018-03-09'),
(13, 'Aspirin 80mg Tab', 15, 3.00, 45, '000001007', '2018-03-09'),
(14, 'Lopermide 200mg', 5, 6.00, 30, '000001007', '2018-03-09'),
(15, 'Biogesic 250mg', 5, 5.00, 25, '000003005', '2018-03-09'),
(16, 'Nifedipine 10mg', 5, 10.00, 50, '000003005', '2018-03-09'),
(17, 'Kispirin 10mg', 1, 500.00, 500, '000003005', '2018-03-09');

-- 
-- Dumping data for table medicine
--
INSERT INTO medicine VALUES
(4, 'Biogesic 250mg', 50, NULL, NULL, 5, '2018-03-10 01:33:57', 'active'),
(5, 'Lopermide 200mg', 50, NULL, NULL, 6, '2018-03-10 01:34:13', 'active'),
(6, 'Mefenamic Acid 250mg', 50, NULL, NULL, 4, '2018-03-10 01:34:50', 'active'),
(7, 'Nifedipine 10mg', 50, NULL, NULL, 10, '2018-03-10 01:35:40', 'active'),
(8, 'Amoxicilin 500mg caps', 50, NULL, NULL, 5, '2018-03-10 01:36:17', 'active'),
(9, 'Aspirin 80mg Tab', 100, NULL, NULL, 3, '2018-03-10 01:36:48', 'active'),
(10, 'Kispirin 10mg', 50, NULL, NULL, 500, '2018-03-10 01:37:06', 'active'),
(11, 'Yakapsule 3mg', 50, NULL, NULL, 100, '2018-03-10 01:37:30', 'active');

-- 
-- Dumping data for table patient_transaction
--
INSERT INTO patient_transaction VALUES
(69, '000001001', '000001', 'Jendy V. Manatad', '1', 1, '2018-03-08 03:20:44', 'heartache', 'Lopermide 200mg 3x/day', NULL, '2018-03-08', '50', 'Inactive', '50', '0', NULL, NULL, NULL, NULL, NULL, NULL, 'No', NULL),
(70, '000001002', '000001', 'Hyacinth Cipres', '1', 1, '2018-03-08 14:44:04', NULL, NULL, NULL, '2018-03-08', '50', 'Inactive', '50', '25', NULL, 50.00, 25, 'Discounts', '', NULL, 'Yes', NULL),
(71, '000002003', '000002', 'Jendy V. Manatad', '2', 1, '2018-03-08 15:21:18', 'qweqe', 'Lopermide 200mg  3x/day', NULL, '2018-03-08', '1150', 'Inactive', '1200', '50', NULL, NULL, NULL, NULL, NULL, NULL, 'No', NULL),
(72, '000001004', '000001', 'Jendy V. Manatad', '1', 1, '2018-03-09 05:50:23', 'Back PAin\r\nToothAche\r\nFever', 'Lopermide 200mg 3x/day\r\nMefenamic 500mg 2x/day', NULL, '2018-03-08', '250', 'Inactive', '300', '50', NULL, NULL, NULL, NULL, NULL, NULL, 'No', NULL),
(73, '000003005', '000003', 'Hyacinth Cipres', '1', 1, '2018-03-10 03:14:15', 'Hilanat Tinoud', 'Diatabs 200mg 3x/day', NULL, '2018-03-08', '765', 'Inactive', '400', '17.5', NULL, 50.00, 383, 'SC', '09028342', NULL, 'Yes', 'Murag Hilanat'),
(74, '000001006', '000001', 'Jendy V. Manatad', '1', 0, '2018-03-09 05:56:45', 'qweqe', 'Lopermide 200mg 3x/day', NULL, '2018-03-09', '50', 'Inactive', '50', '0', NULL, NULL, NULL, NULL, NULL, NULL, 'No', NULL),
(75, '000001007', '000001', 'Jendy V. Manatad', '1', 1, '2018-03-09 06:47:46', NULL, NULL, NULL, '2018-03-09', '1225', 'Inactive', '1300', '75', NULL, NULL, NULL, NULL, NULL, NULL, 'No', NULL),
(77, '000004008', '000004', 'Jendy V. Manatad', 'MCHA-1', 2, '2018-03-09 13:10:47', 'asasd', 'Lopermide 200mg 2x/perday', NULL, '2018-03-09', '2200', 'Inactive', '1100', '0', NULL, 50.00, 1100, 'PWD', '', NULL, 'Yes', NULL),
(82, '000006009', '000006', 'Jendy V. Manatad', 'FCHA-3', 2, '2018-03-09 15:39:54', 'Hilanat Jud', 'Neozep 200mg 3x/day', NULL, '2018-03-09', '2690', 'Inactive', '1500', '155', NULL, 50.00, 1345, 'PWD', '009193717623', NULL, 'Yes', 'Hilanat'),
(83, '0000020010', '000002', 'Gene Rose G Obregon', 'MCHA-2', 5, '2018-03-17 03:33:44', '', 'Lopermide 200mg 3x/day', NULL, '2018-03-10', NULL, 'Active', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Sakit sa Likod');

-- 
-- Dumping data for table patient_vsr
--
INSERT INTO patient_vsr VALUES
(2, '000006009', '38', '120/80', '26/bpm', '50/bpm', '2018-03-09 14:32:57'),
(3, '0000020010', '39', '100/70', '30bpm', '50bpm', '2018-03-10 03:33:34');

-- 
-- Dumping data for table user
--
INSERT INTO user VALUES
(49, '000001', 'GENE ROSE', 'OPALLA', 'OBREGON', '09123124121', 'Female', 'Tinangs', 'DAYAS, CORDOVA', 'Widow', 'Widow', '27', '1991-03-09', 'Active', '2018-03-07 18:10:54'),
(50, '000002', 'HYACINTH MAE', 'G', 'CIPRES', '09234234252', 'Female', 'FREDA CIPRES', 'AGUS, LLC', 'Single', 'Single', '18', '2000-09-09', 'Active', '2018-03-07 18:17:04'),
(51, '000003', 'JURIE', 'MANATAD', 'DACULLO', '09273846274', 'Male', 'MILA DACULLO', 'BUENAVISTA, BOHOL', 'Single', 'Born Again', '24', '1994-06-19', 'Active', '2018-03-07 18:26:18'),
(52, '000004', 'JEFFREY', 'VILLAMOR', 'MANATAD', '09234234243', 'Male', 'CRIS', 'MANILA', 'Single', 'Roman Catholic', '28', '1990-07-12', 'Active', '2018-03-07 18:32:10'),
(53, '000005', 'YVECK', 'T', 'CENECERO', '09623423424', 'Female', 'NIYOG', 'LUSONG', 'Single', 'Born Again', '25', '1993-09-07', 'Active', '2018-03-07 18:34:57'),
(54, '000006', 'MELYN', 'T', 'CENECERO', '09234245239', 'Female', 'TIMI', 'BOHOL', 'Single', 'Roman Catholic', '29', '1989-09-13', 'Active', '2018-03-07 18:36:25'),
(55, '000007', 'GERRY', 'M', 'CENIZA', '09172342342', 'Female', 'LOPER', 'BOHOL', 'Married', 'Roman Catholic', '26', '1991-07-12', 'Active', '2018-03-07 18:38:07');

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;